
export const attendanceStudentRecordConstants = {
    GET_BY_MONTH_REQUEST: 'ATTENDANCE_STUDENT_RECORD_GET_BY_MONTH_REQUEST',
    GET_BY_MONTH_SUCCESS: 'ATTENDANCE_STUDENT_RECORD_GET_BY_MONTH_SUCCESS',
    GET_BY_MONTH_FAILURE: 'ATTENDANCE_STUDENT_RECORD_GET_BY_MONTH_FAILURE',

    ADD_NEW_STUDENT_RECORDS_SUCCESS: 'ADD_NEW_STUDENT_RECORDS_SUCCESS',
    UPDATE_NEW_STUDENT_RECORDS_SUCCESS: 'UPDATE_NEW_STUDENT_RECORDS_SUCCESS',
};
