
export const attendanceStudentRecordConstants = {
    GET_BY_MONTH_REQUEST: 'ATTENDANCE_STUDENT_RECORD_GET_BY_MONTH_REQUEST',
    GET_BY_MONTH_SUCCESS: 'ATTENDANCE_STUDENT_RECORD_GET_BY_MONTH_SUCCESS',
    GET_BY_MONTH_FAILURE: 'ATTENDANCE_STUDENT_RECORD_GET_BY_MONTH_FAILURE',
};
