// file src/constants/MULTIPLE_CHOICE_QUESTION.constants.ts
export const multipleChoiceQuestionConstants = {
    GETALL_REQUEST: 'MULTIPLE_CHOICE_QUESTIONS_GETALL_REQUEST',
    GETALL_SUCCESS: 'MULTIPLE_CHOICE_QUESTIONS_GETALL_SUCCESS',
    GETALL_FAILURE: 'MULTIPLE_CHOICE_QUESTIONS_GETALL_FAILURE',
  
    DELETE_REQUEST: 'MULTIPLE_CHOICE_QUESTION_DELETE_REQUEST',
    DELETE_SUCCESS: 'MULTIPLE_CHOICE_QUESTION_DELETE_SUCCESS',
    DELETE_FAILURE: 'MULTIPLE_CHOICE_QUESTION_DELETE_FAILURE',

    CREATE_REQUEST: 'MULTIPLE_CHOICE_QUESTION_CREATE_REQUEST',
    CREATE_SUCCESS: 'MULTIPLE_CHOICE_QUESTION_CREATE_SUCCESS',
    CREATE_FAILURE: 'MULTIPLE_CHOICE_QUESTION_CREATE_FAILURE',

    UPDATE_REQUEST: 'MULTIPLE_CHOICE_QUESTION_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'MULTIPLE_CHOICE_QUESTION_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'MULTIPLE_CHOICE_QUESTION_UPDATE_FAILURE',
};