// file src/constants/student.constants.ts
export const studentConstants = {
    GETALL_REQUEST: 'STUDENTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'STUDENTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'STUDENTS_GETALL_FAILURE',
  
    DELETE_REQUEST: 'STUDENT_DELETE_REQUEST',
    DELETE_SUCCESS: 'STUDENT_DELETE_SUCCESS',
    DELETE_FAILURE: 'STUDENT_DELETE_FAILURE',

    CREATE_REQUEST: 'STUDENT_CREATE_REQUEST',
    CREATE_SUCCESS: 'STUDENT_CREATE_SUCCESS',
    CREATE_FAILURE: 'STUDENT_CREATE_FAILURE',

    UPDATE_REQUEST: 'STUDENT_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'STUDENT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'STUDENT_UPDATE_FAILURE',
};
